### PR TITLE
Fix some dark mode issues / add back the guide icons

### PR DESCRIPTION
**Pull request by marko-bekhta**
fixes https://github.com/quarkusio/quarkusio.github.io/issues/2007 
+fixes https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.2Eio.20search/near/444013207

The icons disappeared as the bundler property key got updated 😕

### CODE REVIEW

**Comment by gsmet** [comment]
@marko-bekhta was it actually pushed to production? I don't see any changes on the website despite the workflow run in the `Actions` tab.

**Comment by marko-bekhta** [comment]
I think we just need to wait for the quarkus.io to get re-built, so that the new script is fetched... from what it seems the script here https://search.quarkus.io/static/bundle/main.js is updated ...

**Comment by marko-bekhta** [comment]
looks better now 🙈

**Comment by gsmet** [comment]
Cool, thanks!

**Pull request merged**
