### PR TITLE
Add ellipses to the highlighted snippets

### PR DESCRIPTION
**Pull request by marko-bekhta**
See https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/search.2Equarkus.2Eio/near/431900183

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
Still think this is a presentation problem that should be handled in the UI, but... ok.

**Comment by yrodiere** [comment]
BTW, I wouldn't want anyone to think I'm not a nitpicker, so... There's a dedicated unicode character for an ellipsis, which is different from three dots: https://www.toptal.com/designers/htmlarrows/punctuation/horizontal-ellipsis/

**Comment by marko-bekhta** [comment]
> Still think this is a presentation problem that should be handled in the UI

That's why I've opened it as a draft 😃 so you can decide which way to go 🙈

**Comment by yrodiere** [comment]
> > Still think this is a presentation problem that should be handled in the UI
> 
> That's why I've opened it as a draft 😃 so you can decide which way to go 🙈

Right, thanks for opening it. Not in the mood to fight, so let's do this :)

**Comment by marko-bekhta** [comment]
> BTW, I wouldn't want anyone to think I'm not a nitpicker, so... There's a dedicated unicode character for an ellipsis, which is different from three dots: https://www.toptal.com/designers/htmlarrows/punctuation/horizontal-ellipsis/

WOW there's also VERTICAL ELLIPSIS 🙈  never even thought that there was something like that 🙈. let me update the PR.

**Comment by yrodiere** [comment]
> > BTW, I wouldn't want anyone to think I'm not a nitpicker, so... There's a dedicated unicode character for an ellipsis, which is different from three dots: https://www.toptal.com/designers/htmlarrows/punctuation/horizontal-ellipsis/
> 
> WOW there's also VERTICAL ELLIPSIS 🙈 never even thought that there was something like that 🙈. let me update the PR.

And [diagonal](https://www.toptal.com/designers/htmlarrows/math/up-right-diagonal-ellipsis/) :grin: Unicode is wild.

**Comment by ia3andy** [comment]
Thanks @marko-bekhta :)

**Pull request merged**
